baseURL = "https://konohaderek.github.io/Blog_hugo/"
languageCode = "zh-tw"
title = "德瑞克小窩"
theme = "gohugo-theme-ananke"
author = "Derek"
description = "Derek Blog"
paginate = 3 
DefaultContentLanguage = "zh-tw"
SectionPagesMenu = "main"

googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo = ""
  description = ""
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/KonohaDerek"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  background_color_class = "bg-black"
  featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
