baseURL = "http://example.org/"
languageCode = "zh-tw"
title = "德瑞克小窩"
theme = "beautifulhugo"
author = "Derek"
description = "Derek Blog"

[[menu.main]]
  identifier = "tags"
  name = "Tags"
  url = "/tags/"

[[params.social]]
  icon = "github"
  name = "My Github"
  url = "https://github.com/KonohaDerek"

[params.style]
  darkestColor = "#d35050"
  darkColor = "#212121"
  lightColor = "#f5e3e0"
  lightestColor = "#f5f5f5"
  primaryColor = "#ffffff"
